- name: Add ArgoCD Helm chart repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Create ArgoCD namespace in Kubernetes
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: argocd

- name: Install or upgrade ArgoCD using Helm chart
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    values_files:
      - "{{ role_path }}/templates/argocd-values.yaml"
    state: present

- name: Create ArgoCD namespace in Kubernetes
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: argo-rollouts

- name: Install Argo Rollouts using kubectl
  ansible.builtin.shell: |
    kubectl -n argo-rollouts apply -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
