- name: Add Argocd Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Create Argocd namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: argocd

- name: Deploy ArgoCD Helm chart
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    values_files:
      - "{{ role_path }}/templates/argocd-values.yaml"
    state: present
